### ISSUE TITLE
Push Notification error with AWS?

### ISSUE THREAD

**Issue by F3L1X79** [strongloop/loopback-component-push#132]
Hi Loopback team,
Thanks for all the great job done so far.
I got an international app running with LoopbackJS push notifications component.
I actually got this weird error which seems related with AWS, but I can't understand how to solve it:

```
Push Notification error:  Error: 123993035933568:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1293:SSL alert number 46

        at SlabBuffer.use (tls.js:235:18)
        at CleartextStream.read [as _read] (tls.js:455:29)
        at CleartextStream.Readable.read (_stream_readable.js:341:10)
        at EncryptedStream.write [as _write] (tls.js:369:25)
        at doWrite (_stream_writable.js:226:10)
        at writeOrBuffer (_stream_writable.js:216:5)
        at EncryptedStream.Writable.write (_stream_writable.js:183:11)
        at write (_stream_readable.js:602:24)
        at flow (_stream_readable.js:611:7)
        at Socket.pipeOnReadable (_stream_readable.js:643:5)
        at Socket.emit (events.js:92:17)

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    TypeError: Cannot read property 'error' of null
        at SecurePair.error (tls.js:1005:21)
        at EncryptedStream.CryptoStream._done (tls.js:703:22)
        at CleartextStream.onCryptoStreamFinish (tls.js:310:54)
        at CleartextStream.g (events.js:180:16)
        at CleartextStream.emit (events.js:92:17)
        at finishMaybe (_stream_writable.js:360:12)
        at endWritable (_stream_writable.js:367:3)
        at CleartextStream.Writable.end (_stream_writable.js:345:5)
        at CleartextStream.CryptoStream.end (tls.js:641:31)
        at Connection.<anonymous> (/data/API/myAPI/node_modules/loopback-component-push/node_modules/apn/lib/connection.js:194:17)
```

Maybe it's not related to the loopback-component-push, but it seems like it is. I'd really appreciate some help.

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
