### ISSUE TITLE
Push Notification Rethrow non-MySQL errors

### ISSUE THREAD

**Issue by shuurai** [strongloop/loopback-component-push#144]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

The problem did not happen in 1.5.4, but all versions after 1.6.0, seems to throw this error whenever notifyById is called.

### Expected result

Should just return nothing and a null error object.

### Actual result (if bug)

```
2017-01-20T17:36:56.976Z pid:31252 worker:41 TypeError: Cannot set property headersSent of #<OutgoingMessage> which has only a getter
2017-01-20T17:36:56.976Z pid:31252 worker:41     at _clone (/var/lib/strong-pm/svc/1/work/2a6ca6b55583c9fe5a4deb6d8ed96e14927dcf8d.1484933783962/node_modules/clone/clone.js:99:16)
2017-01-20T17:36:56.976Z pid:31252 worker:41     at _clone (/var/lib/strong-pm/svc/1/work/2a6ca6b55583c9fe5a4deb6d8ed96e14927dcf8d.1484933783962/node_modules/clone/clone.js:99:18)
2017-01-20T17:36:56.976Z pid:31252 worker:41     at _clone (/var/lib/strong-pm/svc/1/work/2a6ca6b55583c9fe5a4deb6d8ed96e14927dcf8d.1484933783962/node_modules/clone/clone.js:99:18)
2017-01-20T17:36:56.976Z pid:31252 worker:41     at _clone (/var/lib/strong-pm/svc/1/work/2a6ca6b55583c9fe5a4deb6d8ed96e14927dcf8d.1484933783962/node_modules/clone/clone.js:99:18)
2017-01-20T17:36:56.977Z pid:31252 worker:41     at _clone (/var/lib/strong-pm/svc/1/work/2a6ca6b55583c9fe5a4deb6d8ed96e14927dcf8d.1484933783962/node_modules/clone/clone.js:99:18)
2017-01-20T17:36:56.977Z pid:31252 worker:41     at _clone (/var/lib/strong-pm/svc/1/work/2a6ca6b55583c9fe5a4deb6d8ed96e14927dcf8d.1484933783962/node_modules/clone/clone.js:99:18)
```

### Additional information (Node.js version, LoopBack version, etc)

UBUNTU 14
NODE v0.10.25

**Comment by elimcjah** [comment]
How did you resolve this issue?
