### ISSUE TITLE
APNS Push error

### ISSUE THREAD

**Issue by sw8fbar** [strongloop/loopback-component-push#83]
I'm trying to push notifications to my iOS app and I get the following error when the server tries to send the notification. Could someone please point me to the cause?

```
pushing notification to "5546bdf06c21b74d6eb4ee0f"
events.js:85

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:961:21)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at /Users/ajay/projects/igazab-backend/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/Users/ajay/projects/igazab-backend/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
```
Loopback-component-push version : 1.5.1
Node version : v0.12.2
slc version : v3.1.1

**Comment by sw8fbar** [comment]
I could get this working. This can be closed. The issue was a missing CA file. Once included, it ran without a glitch.
